/**
 * 
 * `ActionsEnum` will define the Actions
 * 
 */
export enum ActionsEnum {
  NETWORK_ERROR = 'NETWORK_ERROR',
  UPDATE_FROM_DATE = 'UPDATE_FROM_DATE',
  UPDATE_TO_DATE = 'UPDATE_TO_DATE',
  UPDATE_HOTEL_LIST = 'UPDATE_HOTEL_LIST',
  SHOW_LOADER = 'SHOW_LOADER',
  UPDATE_FILTERS = 'UPDATE_FILTERS',
  UPDATE_SORT_BY =  'UPDATE_SORT_BY'
}


